
docs_dir: docs
# in order to expose with github page project
site_dir: site

# Project information
site_name: airflow-indexima
site_url: https://geronimo-iia.github.io/airflow-indexima/
site_description: Indexima Airflow integration
site_author: Jerome Guibert

# Repository
repo_name: "geronimo-iia/airflow-indexima"
repo_url: https://github.com/geronimo-iia/airflow-indexima
edit_uri:

# Copyright
copyright: "Copyright © 2019 <a href=\"https://github.com/geronimo-iia/airflow-indexima\">Jerome Guibert</a>"

# Configuration
theme: readthedocs

docs_dir: .cache/mkdocs

site_dir: docs

nav:
  - Home: index.md
  - API:
      - Hooks: airflow_indexima.hooks.indexima.md
      - Operators: airflow_indexima.operators.indexima.md
      - Connection: airflow_indexima.connection.md
      - Hive transport: airflow_indexima.hive_transport.md
      - Uri:
        - Factory: airflow_indexima.uri.factory.md
        - Jdbc: airflow_indexima.uri.jdbc.md
  - About:
      - Contributing: contributing.md
      - Change Log: changelog.md
      - License: license.md
      - Code of Conduct: code_of_conduct.md

# Customization
extra:
  social:
    - type: "github"
      link: "https://github.com/geronimo-iia"


# Extensions
markdown_extensions:
  - markdown.extensions.toc:
      permalink: true
